#include <WG/Local/Detail/Tests/test.h>
#include "../VarDcln.hh"

//Unit Tests.
#define S1 (Foo *)
#define S2 local(Foo)
#define S3 localref(Foo &)
#define S4 const
#define S5 ref
#define S6 const ref

/*
WG_PP_VARDCLN_ISEXPLICIT(S1)
WG_PP_VARDCLN_ISEXPLICIT(S2)
WG_PP_VARDCLN_ISEXPLICIT(S3)
WG_PP_VARDCLN_ISEXPLICIT(S4)
WG_PP_VARDCLN_ISEXPLICIT(S5)
WG_PP_VARDCLN_ISEXPLICIT(S6)

//EXPECTED:
//1
//1
//1
//0
//0
//0
*/

BEGIN WG_PP_VARDCLN_ISEXPLICIT(S1) == 1 END
BEGIN WG_PP_VARDCLN_ISEXPLICIT(S2) == 1 END
BEGIN WG_PP_VARDCLN_ISEXPLICIT(S3) == 1 END
BEGIN WG_PP_VARDCLN_ISEXPLICIT(S4) == 0 END
BEGIN WG_PP_VARDCLN_ISEXPLICIT(S5) == 0 END
BEGIN WG_PP_VARDCLN_ISEXPLICIT(S6) == 0 END
