#ifndef WG_PP_TRANSLATOR_KEYWORDS_HH_
#define WG_PP_TRANSLATOR_KEYWORDS_HH_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <WG/Local/Detail/PP/TokenMatching.hh>

//###########
//Public APIs
//###########

#define WG_PP_KEYWORDS_EAT_HEADKEYWORD(tokens) \
  BOOST_PP_EXPAND( \
    BOOST_PP_CAT(WG_PP_KEYWORDS_EAT_, tokens))

#define WG_PP_KEYWORDS_STARTSWITH_VOID(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_VOID_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_THISU(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_THISU_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_PPESCAPE(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_PPESCAPE_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_LOCAL(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_LOCAL_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_ASSIGNTO(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_ASSIGNTO_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_RETURN(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_RETURN_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_PARAMBIND(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_PARAMBIND_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_PARAMSET(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_PARAMSET_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_MEMBIND(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_MEMBIND_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_MEMSET(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_MEMSET_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_CONST(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_CONST_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_REF(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_REF_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_PARAMS(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_PARAMS_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_VARBIND(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_VARBIND_IMPL(tokens)

#define WG_PP_KEYWORDS_STARTSWITH_VARSET(tokens) \
  WG_PP_KEYWORDS_STARTSWITH_VARSET_IMPL(tokens)

//###########
//Impl Macros
//###########

#define WG_PP_TOKENMATCH_BEGINSWITH_void_void WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_VOID_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_void_)

#define WG_PP_TOKENMATCH_BEGINSWITH_thisu_this_ WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_THISU_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_thisu_)

#define WG_PP_TOKENMATCH_BEGINSWITH_ppescape_ppescape WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_PPESCAPE_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_ppescape_)

#define WG_PP_TOKENMATCH_BEGINSWITH_local_local WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_LOCAL_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_local_)

#define WG_PP_TOKENMATCH_BEGINSWITH_assignto_assignto WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_ASSIGNTO_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_assignto_)

#define WG_PP_TOKENMATCH_BEGINSWITH_return_return WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_RETURN_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_return_)

#define WG_PP_TOKENMATCH_BEGINSWITH_parambind_parambind WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_PARAMBIND_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_parambind_)

#define WG_PP_TOKENMATCH_BEGINSWITH_paramset_paramset WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_PARAMSET_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_paramset_)

#define WG_PP_TOKENMATCH_BEGINSWITH_membind_membind WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_MEMBIND_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_membind_)

#define WG_PP_TOKENMATCH_BEGINSWITH_memset_memset WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_MEMSET_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_memset_)

#define WG_PP_TOKENMATCH_BEGINSWITH_const_const WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_CONST_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_const_)

#define WG_PP_TOKENMATCH_BEGINSWITH_ref_ref WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_REF_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_ref_)

#define WG_PP_TOKENMATCH_BEGINSWITH_params_params WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_PARAMS_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_params_)

#define WG_PP_TOKENMATCH_BEGINSWITH_varbind_varbind WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_VARBIND_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_varbind_)

#define WG_PP_TOKENMATCH_BEGINSWITH_varset_varset WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_KEYWORDS_STARTSWITH_VARSET_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TOKENMATCH_BEGINSWITH_varset_)

#define WG_PP_KEYWORDS_EAT_void
#define WG_PP_KEYWORDS_EAT_thisu
#define WG_PP_KEYWORDS_EAT_local
#define WG_PP_KEYWORDS_EAT_assignto
#define WG_PP_KEYWORDS_EAT_return
#define WG_PP_KEYWORDS_EAT_parambind
#define WG_PP_KEYWORDS_EAT_paramset
#define WG_PP_KEYWORDS_EAT_membind
#define WG_PP_KEYWORDS_EAT_memset
#define WG_PP_KEYWORDS_EAT_const
#define WG_PP_KEYWORDS_EAT_ref
#define WG_PP_KEYWORDS_EAT_params
#define WG_PP_KEYWORDS_EAT_varbind
#define WG_PP_KEYWORDS_EAT_varset

#endif /* WG_PP_TRANSLATOR_KEYWORDS_HH_ */
