#ifndef WG_LOCAL_DETAIL_TRANSLATOR_UTILS_HH_
#define WG_LOCAL_DETAIL_TRANSLATOR_UTILS_HH_

#include <boost/preprocessor.hpp>
#include <WG/Local/Detail/PP/TokenMatching.hh>

//###########
//Public APIs
//###########

#define WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_ERROR(tokens) \
  WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_ERROR_IMPL(tokens)
#define WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_ERROR(tokens) \
  WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_ERROR_IMPL(tokens)

#define WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_DEDUCEDTYPE(tokens) \
  WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_DEDUCEDTYPE_IMPL(tokens)
#define WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_DEDUCEDTYPE(tokens) \
  WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_DEDUCEDTYPE_IMPL(tokens)

#define WG_PP_TRNSLTR_UTILS_ADDTYPENAME(istpl) \
  BOOST_PP_EXPR_IIF(istpl, typename)

#define WG_PP_TRNSLTR_UTILS_TYPEOF(istpl, expr) \
  BOOST_PP_IIF( \
    istpl, \
    BOOST_TYPEOF_TPL, \
    BOOST_TYPEOF) (expr)

//###########
//Impl Macros
//###########

#define WG_PP_TRNSLTR_UTILS_TOKENMATCH_BEGINSWITH_WG_PP_ERROR_WG_PP_ERROR \
  WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_ERROR_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TRNSLTR_UTILS_TOKENMATCH_BEGINSWITH_WG_PP_ERROR_)

#define WG_PP_TRNSLTR_UTILS_MAPTONOTHING_WG_PP_ERROR_WG_PP_ERROR
#define WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_ERROR_IMPL(tokens) \
  BOOST_PP_CAT(WG_PP_TRNSLTR_UTILS_MAPTONOTHING_WG_PP_ERROR_, tokens)

#define WG_PP_TRNSLTR_UTILS_TOKENMATCH_BEGINSWITH_WG_PP_DEDUCEDTYPE_WG_PP_DEDUCEDTYPE \
  WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_DEDUCEDTYPE_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_TRNSLTR_UTILS_TOKENMATCH_BEGINSWITH_WG_PP_DEDUCEDTYPE_)

#define WG_PP_TRNSLTR_UTILS_MAPTONOTHING_WG_PP_DEDUCEDTYPE_WG_PP_DEDUCEDTYPE
#define WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_DEDUCEDTYPE_IMPL(tokens) \
  BOOST_PP_CAT(WG_PP_TRNSLTR_UTILS_MAPTONOTHING_WG_PP_DEDUCEDTYPE_, tokens)

#endif /* WG_LOCAL_DETAIL_TRANSLATOR_UTILS_HH_ */
