#ifndef WG_PP_AUTOFUNCTOR_KEYWORDS_HH_
#define WG_PP_AUTOFUNCTOR_KEYWORDS_HH_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <boost/local_function/detail/preprocessor/keyword/facility/is.hpp>

//###########
//Public APIs
//###########

#define WG_PP_TOKENS_EAT_HEADKEYWORD(tokens) \
  BOOST_PP_EXPAND( \
    BOOST_PP_CAT(WG_PP_EAT_KEYWORD_, tokens))

#define WG_PP_TOKENS_STARTWITH_VOID(tokens) \
  WG_PP_TOKENS_STARTWITH_VOID_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_THISU(tokens) \
  WG_PP_TOKENS_STARTWITH_THISU_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_LOCAL(tokens) \
  WG_PP_TOKENS_STARTWITH_LOCAL_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_ASSIGNTO(tokens) \
  WG_PP_TOKENS_STARTWITH_ASSIGNTO_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_RETURN(tokens) \
  WG_PP_TOKENS_STARTWITH_RETURN_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_PARAMBIND(tokens) \
  WG_PP_TOKENS_STARTWITH_PARAMBIND_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_PARAMSET(tokens) \
  WG_PP_TOKENS_STARTWITH_PARAMSET_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_MEMBIND(tokens) \
  WG_PP_TOKENS_STARTWITH_MEMBIND_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_MEMSET(tokens) \
  WG_PP_TOKENS_STARTWITH_MEMSET_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_CONST(tokens) \
  WG_PP_TOKENS_STARTWITH_CONST_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_REF(tokens) \
  WG_PP_TOKENS_STARTWITH_REF_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_PARAMS(tokens) \
  WG_PP_TOKENS_STARTWITH_PARAMS_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_VARBIND(tokens) \
  WG_PP_TOKENS_STARTWITH_VARBIND_IMPL(tokens)

#define WG_PP_TOKENS_STARTWITH_VARSET(tokens) \
  WG_PP_TOKENS_STARTWITH_VARSET_IMPL(tokens)

//###########
//Impl Macros
//###########

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_void_void (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_VOID_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_void_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_thisu_this_ (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_THISU_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_thisu_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_local_local (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_LOCAL_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_local_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_assignto_assignto (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_ASSIGNTO_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_assignto_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_return_return (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_RETURN_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_return_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_parambind_parambind (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_PARAMBIND_IMPL(tokens) \
    BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_parambind_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_paramset_paramset (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_PARAMSET_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_paramset_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_membind_membind (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_MEMBIND_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_membind_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_memset_memset (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_MEMSET_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_memset_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_const_const (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_CONST_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_const_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_ref_ref (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_REF_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_ref_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_params_params (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_PARAMS_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_params_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_varbind_varbind (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_VARBIND_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_varbind_)

#define WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_varset_varset (1) /* unary */
#define WG_PP_TOKENS_STARTWITH_VARSET_IMPL(tokens) \
  BOOST_LOCAL_FUNCTION_DETAIL_PP_KEYWORD_FACILITY_IS_FRONT( \
    tokens, \
    WG_PP_AUTOFUNCTOR_TOKEN_MATCHES_varset_)

#define WG_PP_EAT_KEYWORD_void
#define WG_PP_EAT_KEYWORD_thisu
#define WG_PP_EAT_KEYWORD_local
#define WG_PP_EAT_KEYWORD_assignto
#define WG_PP_EAT_KEYWORD_return
#define WG_PP_EAT_KEYWORD_parambind
#define WG_PP_EAT_KEYWORD_paramset
#define WG_PP_EAT_KEYWORD_membind
#define WG_PP_EAT_KEYWORD_memset
#define WG_PP_EAT_KEYWORD_const
#define WG_PP_EAT_KEYWORD_ref
#define WG_PP_EAT_KEYWORD_params
#define WG_PP_EAT_KEYWORD_varbind
#define WG_PP_EAT_KEYWORD_varset

#endif /* WG_PP_AUTOFUNCTOR_KEYWORDS_HH_ */
