#ifndef WG_PP_LCLCLASS_KEYWORDS_HH_
#define WG_PP_LCLCLASS_KEYWORDS_HH_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <WG/Local/Detail/PP/TokenMatching.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLCLASS_KEYWORDS_EAT_HEADKEYWORD(tokens) \
  BOOST_PP_EXPAND( \
    BOOST_PP_CAT(WG_PP_LCLCLASS_KEYWORDS_EAT_, tokens))

#define WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_DERIVES(tokens) \
  WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_DERIVES_IMPL(tokens)

#define WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_MEMEXT(tokens) \
  WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_MEMEXT_IMPL(tokens)

#define WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_MEMINT(tokens) \
  WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_MEMINT_IMPL(tokens)

//###########
//Impl Macros
//###########

#define WG_PP_LCLCLASS_KEYWORDS_BEGINSWITH_derives_derives WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_DERIVES_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCLASS_KEYWORDS_BEGINSWITH_derives_)

#define WG_PP_LCLCLASS_KEYWORDS_BEGINSWITH_memext_memext WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_MEMEXT_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCLASS_KEYWORDS_BEGINSWITH_memext_)

#define WG_PP_LCLCLASS_KEYWORDS_BEGINSWITH_memint_memint WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCLASS_KEYWORDS_STARTSWITH_MEMINT_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCLASS_KEYWORDS_BEGINSWITH_memint_)

#define WG_PP_LCLCLASS_KEYWORDS_EAT_derives
#define WG_PP_LCLCLASS_KEYWORDS_EAT_memext
#define WG_PP_LCLCLASS_KEYWORDS_EAT_memint

#endif /* WG_PP_LCLCLASS_KEYWORDS_HH_ */
