#ifndef WG_PP_LCLCONTEXT_NAMES_HH_
#define WG_PP_LCLCONTEXT_NAMES_HH_

#include <WG/Local/Detail/PP/Translator/BackEnd/ID.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLCONTEXT_NAMES_MANGLE(name) \
  WG_PP_ID_CAT( \
    WG_PP_ID_MAKE_GLOBAL(lclcontext), \
    name)

#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_ALIASROOTNAME() \
  WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_ALIASROOTNAME_IMPL()
#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_CLASSNAME() \
  WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_CLASSNAME_IMPL()

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGR_AUTOSIMFLAGNAME() \
  WG_PP_LCLCONTEXT_NAMES_SCOPEMNGR_AUTOSIMFLAGNAME_IMPL()

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGR_OBJNAME(indx) \
  WG_PP_LCLCONTEXT_NAMES_SCOPEMNGR_OBJNAME_IMPL(indx)

#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_CLASSNAME(indx) \
  WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_CLASSNAME_IMPL(indx)

//###########
//Impl Macros
//###########

//--------------
//ENTEREDASDCLNS
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_ALIASROOTNAME_IMPL() \
  type

#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_CLASSNAME_IMPL() \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_MANGLE(typealiaser), \
    enteredas_dclns)

//--------------
//ADHOCSCOPEMNGR
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_CLASSNAME_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_MANGLE(adhoc_scopemngr_type), \
    indx)

//---------
//SCOPEMNGR
//---------

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGR_OBJNAME_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_MANGLE(scopemngr), \
    indx)

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGR_AUTOSIMFLAGNAME_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_MANGLE(autosimflag)

#endif /* WG_PP_LCLCONTEXT_NAMES_HH_ */
