#ifndef WG_PP_LCLCONTEXT_NAMES_HH_
#define WG_PP_LCLCONTEXT_NAMES_HH_

#include <WG/Local/Detail/PP/Translator/BackEnd/ID.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_ALIASROOTNAME() \
  WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_ALIASROOTNAME_IMPL()
#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_CLASSNAME() \
  WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_CLASSNAME_IMPL()

#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_BASECLASSNAME(indx) \
  WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_BASECLASSNAME_IMPL(indx)
#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_CLASSNAME(indx) \
  WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_CLASSNAME_IMPL(indx)
#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_OBJNAME(indx) \
  WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_OBJNAME_IMPL(indx)

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGRGRP_OBJNAME() \
  WG_PP_LCLCONTEXT_NAMES_SCOPEMNGRGRP_OBJNAME_IMPL()
#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGRGRP_AUTOSIMFLAGNAME() \
  WG_PP_LCLCONTEXT_NAMES_SCOPEMNGRGRP_AUTOSIMFLAGNAME_IMPL()

//###########
//Impl Macros
//###########

//------
//Utils.
//------

#define WG_PP_LCLCONTEXT_NAMES_GLOBALID() WG_PP_ID_MAKE_GLOBAL(lclcontext)

#define WG_PP_LCLCONTEXT_NAMES_FORMATNAME(name) \
  WG_PP_ID_CAT(WG_PP_LCLCONTEXT_NAMES_GLOBALID(), name)

#define WG_PP_LCLCONTEXT_NAMES_TYPEALIASER_NAME(classname) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(typealiaser), \
    classname)

//--------------
//ENTEREDASDCLNS
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_ALIASROOTNAME_IMPL() \
  type

#define WG_PP_LCLCONTEXT_NAMES_ENTEREDASDCLNS_TYPEALIASOR_CLASSNAME_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_TYPEALIASER_NAME( enteredas_dclns )

//--------------
//ADHOCSCOPEMNGR
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_BASECLASSNAME_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(adhoc_scope_mngr_base), \
    indx)

#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_CLASSNAME_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(adhoc_scope_mngr), \
    indx)

#define WG_PP_LCLCONTEXT_NAMES_ADHOCSCOPEMNGR_OBJNAME_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(adhoc_scope_mngr_obj), \
    indx)

//------------
//SCOPEMNGRGRP
//------------

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGRGRP_OBJNAME_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_FORMATNAME(scope_mngr_grp)

#define WG_PP_LCLCONTEXT_NAMES_SCOPEMNGRGRP_AUTOSIMFLAGNAME_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_FORMATNAME(autosimflag)

#endif /* WG_PP_LCLCONTEXT_NAMES_HH_ */
