#ifndef WG_PP_LCLFUNCTION_KEYWORDS_HH_
#define WG_PP_LCLFUNCTION_KEYWORDS_HH_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <WG/Local/Detail/PP/TokenMatching.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLFUNCTION_KEYWORDS_EAT_HEADKEYWORD(tokens) \
  BOOST_PP_EXPAND( \
    BOOST_PP_CAT(WG_PP_LCLFUNCTION_KEYWORDS_EAT_, tokens))

#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_RETURN(tokens) \
  WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_RETURN_IMPL(tokens)

#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_PARAMS(tokens) \
  WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_PARAMS_IMPL(tokens)

#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARBIND(tokens) \
  WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARBIND_IMPL(tokens)

#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARSET(tokens) \
  WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARSET_IMPL(tokens)

//###########
//Impl Macros
//###########

#define WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_return_return WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_RETURN_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_return_)

#define WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_params_params WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_PARAMS_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_params_)

#define WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_varbind_varbind WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARBIND_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_varbind_)

#define WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_varset_varset WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARSET_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLFUNCTION_KEYWORDS_BEGINSWITH_varset_)

#define WG_PP_LCLFUNCTION_KEYWORDS_EAT_return
#define WG_PP_LCLFUNCTION_KEYWORDS_EAT_params
#define WG_PP_LCLFUNCTION_KEYWORDS_EAT_varbind
#define WG_PP_LCLFUNCTION_KEYWORDS_EAT_varset

#endif /* WG_PP_LCLFUNCTION_KEYWORDS_HH_ */
