#include <WG/Local/Tests/Utils/PreprocessorUnitTester.hh>
#include <WG/Local/Detail/PP/Tests/Util.hh>
#include <WG/Local/Detail/PP/Seq.hh>

int const BOOST_PP_NIL = 123456789;

#define SN1 BOOST_PP_NIL
#define SN2 BOOST_PP_NIL
#define S1 (1)
#define S2 (2)(3)
#define S3 (4)(5)(6)

// SEQ_ISNIL
BEGIN WG_PP_SEQ_ISNIL(SN1) == 1 END
BEGIN WG_PP_SEQ_ISNIL(S1) == 0 END
WG_PP_TESTS_UTIL_MACROEXPANDSTOID( \
  WG_PP_SEQ_ISNIL(blah blah blah), \
  WG_PP_ERROR_INVALID_ARGUMENT)

// SEQ_IS_INDEX_LAST
BEGIN WG_PP_SEQ_IS_INDEX_LAST(3, 1) == 0 END
BEGIN WG_PP_SEQ_IS_INDEX_LAST(3, 2) == 1 END

// SEQ_CAT
BEGIN WG_PP_SEQ_CAT(SN1) == BOOST_PP_NIL END
BEGIN WG_PP_SEQ_CAT(S1) == 1 END
BEGIN WG_PP_SEQ_CAT(S2) == 23 END

// SEQ_ELEM
BEGIN WG_PP_SEQ_ELEM(1, SN1) == BOOST_PP_NIL END
BEGIN WG_PP_SEQ_ELEM(BOOST_PP_NIL, S2) == BOOST_PP_NIL END
BEGIN WG_PP_SEQ_ELEM(1, S3) == 5 END

// SEQ_JOIN
BEGIN WG_PP_SEQ_JOIN_ARG2(SN1,SN2) == BOOST_PP_NIL END
BEGIN WG_PP_SEQ_CAT( WG_PP_SEQ_JOIN_ARG2(SN1,S1) ) == 1 END
BEGIN WG_PP_SEQ_CAT( WG_PP_SEQ_JOIN_ARG3(SN1, S1, S2) ) == 123 END
BEGIN WG_PP_SEQ_CAT( WG_PP_SEQ_JOIN_ARG4(SN1, S1, S2, S3) ) == 123456 END

// SEQ_REPLACE
BEGIN WG_PP_SEQ_REPLACE(SN1, 0, foo) == BOOST_PP_NIL END
BEGIN WG_PP_SEQ_REPLACE(S1, BOOST_PP_NIL, bar) == 1 END
BEGIN WG_PP_SEQ_CAT( WG_PP_SEQ_REPLACE(S2, 1, 5) ) == 25 END

// SEQ_SIZE
BEGIN WG_PP_SEQ_SIZE(SN1) == 0 END
BEGIN WG_PP_SEQ_SIZE(S3) == 3 END
