#ifndef WG_PP_LCLCONTEXT_KEYWORDS_HH_
#define WG_PP_LCLCONTEXT_KEYWORDS_HH_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <WG/Local/Detail/PP/TokenMatching.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(tokens) \
  BOOST_PP_EXPAND( \
    BOOST_PP_CAT(WG_PP_LCLCONTEXT_KEYWORDS_EAT_, tokens))

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_AS(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_AS_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONBIND(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONBIND_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONSET(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONSET_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONTHROW(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONTHROW_IMPL(tokens)

//###########
//Impl Macros
//###########

#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_with
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_as
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_anonbind
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_anonset
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_onenter
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_onexit
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_onthrow

#define WG_PP_LCLCONTEXT_KEYWORDS_with_with WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_with_)

#define WG_PP_LCLCONTEXT_KEYWORDS_as_as WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_AS_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_as_)

#define WG_PP_LCLCONTEXT_KEYWORDS_anonbind_anonbind WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONBIND_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_anonbind_)

#define WG_PP_LCLCONTEXT_KEYWORDS_anonset_anonset WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONSET_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_anonset_)

#define WG_PP_LCLCONTEXT_KEYWORDS_onenter_onenter WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_onenter_)

#define WG_PP_LCLCONTEXT_KEYWORDS_onexit_onexit WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_onexit_)

#define WG_PP_LCLCONTEXT_KEYWORDS_onthrow_onthrow WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONTHROW_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_onthrow_)

#endif /* WG_PP_LCLCONTEXT_KEYWORDS_HH_ */
