#ifndef WG_PP_LCLCONTEXT_KEYWORDS_HH_
#define WG_PP_LCLCONTEXT_KEYWORDS_HH_

#include <boost/preprocessor/cat.hpp>
#include <boost/preprocessor/facilities/expand.hpp>
#include <WG/Local/Detail/PP/TokenMatching.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(tokens) \
  BOOST_PP_EXPAND( \
    BOOST_PP_CAT(WG_PP_LCLCONTEXT_KEYWORDS_EAT_, tokens))

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ENTERAS(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ENTERAS_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHRAII(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHRAII_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHADHOC(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHADHOC_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER_IMPL(tokens)

#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT(tokens) \
  WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT_IMPL(tokens)

//###########
//Impl Macros
//###########

#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_with
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_enter_as
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_with_raii
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_with_adhoc
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_on_enter
#define WG_PP_LCLCONTEXT_KEYWORDS_EAT_on_exit

#define WG_PP_LCLCONTEXT_KEYWORDS_with_with WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_with_)

#define WG_PP_LCLCONTEXT_KEYWORDS_enter_as_enter_as WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ENTERAS_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_enter_as_)

#define WG_PP_LCLCONTEXT_KEYWORDS_with_raii_with_raii WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHRAII_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH( \
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_with_raii_)

#define WG_PP_LCLCONTEXT_KEYWORDS_with_adhoc_with_adhoc WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHADHOC_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_with_adhoc_)

#define WG_PP_LCLCONTEXT_KEYWORDS_on_enter_on_enter WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_on_enter_)

#define WG_PP_LCLCONTEXT_KEYWORDS_on_exit_on_exit WG_PP_TOKENMATCH_FRONTMATCH
#define WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT_IMPL(tokens) \
  WG_PP_TOKENMATCH_BEGINSWITH(\
    tokens, \
    WG_PP_LCLCONTEXT_KEYWORDS_on_exit_)

#endif /* WG_PP_LCLCONTEXT_KEYWORDS_HH_ */
