#include <WG/Local/Tests/test.h>
#include <WG/Local/Detail/PP/Translator/Keywords.hh>

// WG_PP_KEYWORDS_EAT_HEADKEYWORD
BEGIN WG_PP_KEYWORDS_EAT_HEADKEYWORD(void 1) END
BEGIN WG_PP_KEYWORDS_EAT_HEADKEYWORD(this_ 1) END
BEGIN WG_PP_KEYWORDS_EAT_HEADKEYWORD(type 1) END
BEGIN WG_PP_KEYWORDS_EAT_HEADKEYWORD(local 1) END
BEGIN WG_PP_KEYWORDS_EAT_HEADKEYWORD(const 1) END
BEGIN WG_PP_KEYWORDS_EAT_HEADKEYWORD(ref 1) END

BEGIN WG_PP_KEYWORDS_STARTSWITH_VOID(void foo) END
BEGIN WG_PP_KEYWORDS_STARTSWITH_THISU(this_ foo) END
BEGIN WG_PP_KEYWORDS_STARTSWITH_TYPE(type foo) END
BEGIN WG_PP_KEYWORDS_STARTSWITH_LOCAL(local foo) END
BEGIN WG_PP_KEYWORDS_STARTSWITH_CONST(const foo) END
BEGIN WG_PP_KEYWORDS_STARTSWITH_REF(ref foo) END
