#include <WG/Local/Tests/test.h>
#include <WG/Local/Detail/PP/Translator/Utils.hh>

// WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_DEDUCEDTYPE
BEGIN WG_PP_TRNSLTR_UTILS_STARTSWITH_WG_PP_DEDUCEDTYPE(WG_PP_DEDUCEDTYPE foo) == 1 END

// WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_DEDUCEDTYPE
BEGIN WG_PP_TRNSLTR_UTILS_EATHEADTOKEN_WG_PP_DEDUCEDTYPE(WG_PP_DEDUCEDTYPE 1) == 1 END
