#include <WG/Local/Tests/test.h>
#include <WG/Local/Detail/PP/Translator/FrontEnd/LclFunction/Keywords.hh>

BEGIN WG_PP_LCLFUNCTION_KEYWORDS_EAT_HEADKEYWORD(return 1) END
BEGIN WG_PP_LCLFUNCTION_KEYWORDS_EAT_HEADKEYWORD(params 1) END
BEGIN WG_PP_LCLFUNCTION_KEYWORDS_EAT_HEADKEYWORD(varbind 1) END
BEGIN WG_PP_LCLFUNCTION_KEYWORDS_EAT_HEADKEYWORD(varset 1) END

BEGIN WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_RETURN(return foo) END
BEGIN WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_PARAMS(params foo) END
BEGIN WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARBIND(varbind foo) END
BEGIN WG_PP_LCLFUNCTION_KEYWORDS_STARTSWITH_VARSET(varset foo) END
