#include <WG/Local/Tests/Utils/PreprocessorUnitTester.hh>
#include <WG/Local/Detail/PP/Translator/FrontEnd/LclContext/Keywords.hh>

// WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(with 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(enter_as 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(with_raii 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(with_adhoc 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(on_enter 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(on_exit 1) END

BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH(with FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ENTERAS(enter_as FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHRAII(with_raii FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHADHOC(with_adhoc FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER(on_enter FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT(on_exit FOO) END
