#include <WG/Local/Tests/Utils/PreprocessorUnitTester.hh>
#include <WG/Local/Detail/PP/Translator/FrontEnd/LclContext/Keywords.hh>

// WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(with 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(entered_as 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(with_adhoc 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(onenter 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(onexit 1) END

BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH(with FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ENTEREDAS(entered_as FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITHADHOC(with_adhoc FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER(onenter FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT(onexit FOO) END
