#include <WG/Local/Tests/test.h>
#include <WG/Local/Detail/PP/Translator/FrontEnd/LclContext/Keywords.hh>

// WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(with 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(as 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(anonbind 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(anonset 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(onenter 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(onexit 1) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_EAT_HEADKEYWORD(onthrow 1) END

BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_WITH(with FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_AS(as FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONBIND(anonbind FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ANONSET(anonset FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONENTER(onenter FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONEXIT(onexit FOO) END
BEGIN WG_PP_LCLCONTEXT_KEYWORDS_STARTSWITH_ONTHROW(onthrow FOO) END
