#ifndef WG_PP_LCLCONTEXT_NAMES_HH_
#define WG_PP_LCLCONTEXT_NAMES_HH_

#include <WG/Local/Detail/PP/Translator/BackEnd/ID.hh>

//###########
//Public APIs
//###########

#define WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSYNTAXCHECKER_CNTXTMNGRDCLNS() \
  WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSYNTAXCHECKER_CNTXTMNGRDCLNS_IMPL()
#define WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_CNTXTMNGRDCLNS() \
  WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_CNTXTMNGRDCLNS_IMPL()

#define WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSYNTAXCHECKER_ENTEREDASDCLNS() \
  WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSYNTAXCHECKER_ENTEREDASDCLNS_IMPL()
#define WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_ENTEREDASDCLNS() \
  WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_ENTEREDASDCLNS_IMPL()

#define WG_PP_LCLCONTEXT_NAMES_ADHOCCNTXTMNGR_CLASS(indx) \
  WG_PP_LCLCONTEXT_NAMES_ADHOCCNTXTMNGR_CLASS_IMPL(indx)
#define WG_PP_LCLCONTEXT_NAMES_ADHOCCNTXTMNGR_OBJ(indx) \
  WG_PP_LCLCONTEXT_NAMES_ADHOCCNTXTMNGR_OBJ_IMPL(indx)

#define WG_PP_LCLCONTEXT_NAMES_CNTXTMNGRGRP_CLASS() \
  WG_PP_LCLCONTEXT_NAMES_CNTXTMNGRGRP_CLASS_IMPL()
#define WG_PP_LCLCONTEXT_NAMES_CNTXTMNGRGRP_OBJ() \
  WG_PP_LCLCONTEXT_NAMES_CNTXTMNGRGRP_OBJ_IMPL()

//###########
//Impl Macros
//###########

//------
//Utils.
//------

#define WG_PP_LCLCONTEXT_NAMES_GLOBALID() WG_PP_ID_MAKE_GLOBAL(lclcontext)

#define WG_PP_LCLCONTEXT_NAMES_FORMATNAME(name) \
  WG_PP_ID_CAT(WG_PP_LCLCONTEXT_NAMES_GLOBALID(), name)

#define WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSSYNTAXCHECKER_NAME(classname) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(localoperandsyntaxchecker), \
    WG_PP_ID_CAT( \
      classname, \
      __LINE__))

#define WG_PP_LCLCONTEXT_NAMES_TYPEALIASER_NAME(classname) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(typealiaser), \
    WG_PP_ID_CAT( \
      classname, \
      __LINE__))

//--------------
//CNTXTMNGRDCLNS
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ROOT_CNTXTMNGRDCLNS() cntxtmngr_dclns

#define WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSYNTAXCHECKER_CNTXTMNGRDCLNS_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSSYNTAXCHECKER_NAME( \
    WG_PP_LCLCONTEXT_NAMES_ROOT_CNTXTMNGRDCLNS() )

#define WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_CNTXTMNGRDCLNS_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_TYPEALIASER_NAME( \
    WG_PP_LCLCONTEXT_NAMES_ROOT_CNTXTMNGRDCLNS() )

//--------------
//ENTEREDASDCLNS
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ROOT_ENTEREDASDCLNS() enteredas_dclns

#define WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSYNTAXCHECKER_ENTEREDASDCLNS_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_LOCALOPERANDSSYNTAXCHECKER_NAME( \
    WG_PP_LCLCONTEXT_NAMES_ROOT_ENTEREDASDCLNS() )

#define WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_ENTEREDASDCLNS_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_TYPEALIASOR_CNTXTMNGRDCLNS_IMPL( \
    WG_PP_LCLCONTEXT_NAMES_ROOT_ENTEREDASDCLNS() )

//--------------
//ADHOCCNTXTMNGR
//--------------

#define WG_PP_LCLCONTEXT_NAMES_ROOT_ADHOCCNTXTMNGR() adhoc_cntxtmngr

#define WG_PP_LCLCONTEXT_NAMES_ADHOCCNTXTMNGR_CLASS_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(adhoc_cntxtmngr), \
    indx)

#define WG_PP_LCLCONTEXT_NAMES_ADHOCCNTXTMNGR_OBJ_IMPL(indx) \
  WG_PP_ID_CAT( \
    WG_PP_LCLCONTEXT_NAMES_FORMATNAME(adhoc_cntxtmngr_obj), \
    indx)

//------------
//CNTXTMNGRGRP
//------------

#define WG_PP_LCLCONTEXT_NAMES_CNTXTMNGRGRP_CLASS_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_FORMATNAME(context_mngr_grp)

#define WG_PP_LCLCONTEXT_NAMES_CNTXTMNGRGRP_OBJ_IMPL() \
  WG_PP_LCLCONTEXT_NAMES_FORMATNAME(context_mngr_grp_obj)

#endif /* WG_PP_LCLCONTEXT_NAMES_HH_ */
